config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'top' => "homes#top"
  post "books" => "books#create"
  get 'books' => "books#index"
  get 'books/:id' => "books#show", as: "book"
  get 'top' => "homes#top"
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  def create
  	@book = Book.new(book_params)
  	if @book.save
  	  flash[:notice] = "Book was successfully created."
  		redirect_to book_path(@book)
  	else
  	  @books = Book.all
  		render :index
  	end
  end
  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <p><%= flash[:notice] %></p>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

	<%= f.label :Title %><br/>
	<%= f.text_field :title %>

	<br><%= f.label :Body %><br/>
	<%= f.text_area :body %>

	<br><%= f.submit 'Update Book' %></br>
	 <%= link_to "show", book_path(@book.id) %>
  |
  <%= link_to "back", "/books" %>

<% end %>

app/views/books/index.html.erb
<%= flash[:notice] %>
<h3>Books</h3>
<table>
	<thead>
		<tr>
			<th>title</th>
			<th>body</th>
			<th></th>
		</tr>
	</thead>
	
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to "show", book_path(book.id) %></td>
			<td><%= link_to "edit", edit_book_path(book.id) %></td>
			<td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "削除しますか？" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<h3>New book</h3>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url:"/books", method: :post do |f| %>

	<%= f.label :Title %><br/>
	<%= f.text_field :title %>

	<br><%= f.label :Body %><br/>
	<%= f.text_area :body %>

	<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/new.html.erb
<h3>Books</h3>


<table>
	<thead>
		<tr>
			<th>title</th>
			<th>body</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to "show", book_path(book.id) %></td>
			<td><%= link_to "edit", edit_book_path(book.id) %></td>
			<td><%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<h3>New book</h3>
<% if @book.errors.any? %>
  <%= @book.errors.count %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 
<%= form_with model: @book, url:"/books", method: :post do |f| %>

	<%= f.label :Title %><br/>
	<%= f.text_field :title %>

	<br><%= f.label :Body %><br/>
	<%= f.text_area :body %>

	<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>
<p>
  <strong>title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>body:</strong>
  <%= @book.body %>
</p>
<span>
  <%= link_to "edit", edit_book_path(@book.id) %>
  |
  <%= link_to "back", "/books" %>
</span>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>
<p>
  <strong>Bookers</strong>では、さまざまな書籍にかんするあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
</p>
<a href="/books">start</a></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>